version: "3.9"

services:

  frontend:
    image: nginx-frontend
    build:
      context: ./frontend
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - api
    networks:
      - backend

  api:
    image: nginx-backend
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - backend
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - db
      


networks: 
  backend:
  db: