version: "3.9"

services:

  frontend:
    image: nginx-frontend
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - frontend
      - backend

  api:
    image: nginx-backend
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - backend
      - db

  db:
    image: mongo:latest
    networks:
      - db
      


networks: 
  frontend:
  backend:
  db: